### ISSUE TITLE
Properly Rewrite Markdown links/image references

### ISSUE THREAD

**Issue by martinklepsch** [martinklepsch/cljdoc#12]
We currently take Markdown and Asciidoc files from projects and render them. For projects that don't provide a [doctree](https://github.com/martinklepsch/cljdoc/blob/master/doc/adr/0007-introduce-doctrees-to-describe-non-api-docs.md) we take the README for others we take multiple files from the projects Git repository. 

Given that most of these Markdown/Asciidoc files were written with GitHub (or something else) in mind some of the links might be relative and will only work when the file is rendered on a specific server at a specific location.

To fix this, I initially [implemented some CommonMark extensions](https://github.com/martinklepsch/cljdoc/blob/94150fea4ee6e666a7f8d139d7405c02084e1e03/src/cljdoc/renderers/markup.clj#L34-L60) and the approach seemed to work. Based on the doctree and other information on the repository we can derive a file's actual location, either on cljdoc or on another platform like GitHub.

Now CommonMark is Markdown specific, and really we should implement those transforms on top of some HTML abstraction (zippers/hiccup/whatever).

So a function needs to be written:

- **Inputs**
  - doctree
  - information about repo (scm url, commit sha, other files(?)...)
  - some form of HTML that might contain broken links when rendered on cljdoc
- **Output**
   - some form of HTML with those links fixed as best as possible

**Comment by arrdem** [comment]
ugh this is literally what stacks is supposed to do 👻

**Comment by martinklepsch** [comment]
@arrdem that's interesting, it's not something I derived from the current state of the [stacks](https://github.com/arrdem/stacks) repo but if stacks eventually supports this I'd be happy to consider using it 🙂

**Comment by martinklepsch** [comment]
Made some good progress with that (https://github.com/martinklepsch/cljdoc/commit/233ce49c40385ceeddce8793003e902c6078b293), for now all that's missing to close this issue is some logging when we can't fix a relative link.

**Comment by martinklepsch** [comment]
Closing this now. There's fallbacks in place if we can't fix a link.
