### ISSUE TITLE
Markdown table is broken

### ISSUE THREAD

**Issue by ikitommi** [martinklepsch/cljdoc#29]
* in https://cljdoc.xyz/d/metosin/reitit/0.1.0/doc/advanced/configuring-routers/
* original https://github.com/metosin/reitit/blob/master/doc/advanced/configuring_routers.md

**Comment by martinklepsch** [comment]
I haven't tested but I think that the reason might be that the rows are not "closed", e.g. there's no trailing `|` delimiting a row. In GitHub's documentation that syntax isn't mentioned, do you think it should work?

**Comment by ikitommi** [comment]
Closed the rows, could the docs be refreshed? https://cljdoc.xyz/d/metosin/reitit/0.1.1/doc/advanced/configuring-routers/

**Comment by martinklepsch** [comment]
Closing this as the problem that we have now is captured in #31.

**Comment by ikitommi** [comment]
The closed rows didn't help btw: https://cljdoc.xyz/d/metosin/reitit/0.1.2-SNAPSHOT/doc/advanced/configuring-routers/

**Comment by ikitommi** [comment]
I think I fixed this, there was an extra whitespace in the header separator-row. Pushed new SNAPSHOT into Clojars. Just need to figure out how to update the docs... ;)
