### ISSUE TITLE
An Update For People Following Along

### ISSUE THREAD

**Issue by martinklepsch** [martinklepsch/cljdoc#3]
> You can also read this update in [doc/updates/0001-hello-everyone.md](https://github.com/martinklepsch/cljdoc/blob/master/doc/updates/0001-hello-everyone.md)

Hello everyone following along! :wave:

This is intended as an update so you know what has been going on.

First of all, something to see (don't get settled on it, I expect things to change a lot):

![an early preview](https://github.com/martinklepsch/cljdoc/blob/master/doc/updates/0001-hello-everyone.png?raw=true)

Over the last two weeks I created a system that runs [Codox](https://github.com/weavejester/codox) on arbitrary Jars from Clojars and stores metadata about them in a [Grimoire](https://github.com/clojure-grimoire/lib-grimoire) store. Think of the Grimoire store as a global repository of static analysis done on Clojure code. The :sparkles: **plain data** :sparkles: inside that store can help answer questions like:

- What functions are available in a namespace for a given platform?
- What namespaces are in an artifact?

And will allow us to build various tools on top, including: static HTML pages (see picture), Docsets for documentation browsers, single page apps.

I've also had a very productive chat with Reid McKenzie  (@arrdem, author of Grimoire) about how we could extend the Grimoire data model to accommodate non-API documentation. This is something Reid has been thinking about for a long time and so the discussion with him has been invaluable. I'd really like to see this done for a v1 of this project.

In the last 6 days I authored 116 commits and [wrote five Architecture Decision Records](https://github.com/martinklepsch/cljdoc/tree/master/doc/adr)  ([?](http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions)) hoping that this may make it easier for others to trace my decision making. The repo is two weeks old but most of the work has been done in the last week.

I also talked to Daniel Compton who is part of the Clojars team and he outlined the possibility of transitioning this project into the Clojars organisation to ensure it's longevity (yay!). Nothing is set in stone and there's still a lot more work to do though.

While the README has served as a TODO list so far it seems that this is a good time to also adopt some processes that work better with additional contributors. In the coming days I will add a `CONTRIBUTING.md` file, create issues and establish some basic tag hierarchy. I hope this helps people interested in contributing find the kind of stuff they enjoy working on.

Maybe I'm just a little over-hyped by working a bit too much on this but — if my current vision for this doesn't have any major blockers — Clojure/Script should have some of the best documentation tooling out there once we're "done" here.

:v: Martin

**Comment by martinklepsch** [comment]
Already added [`CONTRIBUTING.md`](https://github.com/martinklepsch/cljdoc/blob/master/CONTRIBUTING.md) with some areas where people could hepl.

**Comment by plexus** [comment]
Thank you so much for working on this Martin! And really impressive work so far!

**Comment by DjebbZ** [comment]
> Clojure/Script should have some of the best documentation tooling out there once we're "done" here.

Better than Rust ? (Honest question).

**Comment by martinklepsch** [comment]
> Better than Rust?

That's a very broad question to answer but I found [docs.rs](https://docs.rs/) and this [documentation for Rayon](https://docs.rs/rayon/0.9.0/rayon/) and will use that as a point of comparison. If you have specific aspects about the documentation of Rust libraries that you admire or a particular library that does a great job, let me know. 

- First of all it's important to point out that I wrote "documentation tooling" not "documentation". Besides making API- other docs easy to publish and maintain there's very little that one can do that scales to the entire ecosystem. **Projects will still be responsible for their documentation.**
- From what I can see looking at the Rust docs all non API documentation is generated from comments inside source files. Co-located documentation is definitely useful — and we have that too in the ns form — but often is not as useful when trying to explain how different modules may interact.
- For module-spanning documentation you usually want some separate text files that relate different things to each other. The plan I'm pursuing here is that you can author these kinds of text files as part of the `doc/` folder in your repository and they will show up in your documentation (also versioned of course). 
- Besides API docs and articles I'm also very excited to integrate examples and other auxiliary data into the Grimoire store. There's no final design yet but this likely means that people will be able to attach examples to individual functions, namespaces or even an entire project. 
- [docs.rs](https://docs.rs/) allows you to jump between versions, platforms and view all sorts of other metadata. We will have that too. 

Obviously `docs.rs` is much more mature in what it does and it will take some time for `cljdoc` (other name suggestions welcome btw) to reach a similar maturity. That said I'm aiming for a limited roll-out in February or March. We'll see.

PS. If you feel like staying in the loop consider "watching" the project.

**Comment by DjebbZ** [comment]
Something else I like about Rust doc ecosystem is that Cargo (the build tool) is able to generate all docs for all libs included in a project, including Rust itself, in static website.

I'm going to follow your advances. Your vision is interesting. Watching.

**Comment by DjebbZ** [comment]
There's this site http://www.newrustacean.com/show_notes/ which is a podcast about Rust. The interesting thing about it is that it's generated from source code, as if the podcast notes were a normal Rust package. A bit crazy idea but I like it. Just sharing as food for thought.

**Comment by roman01la** [comment]
> Something else I like about Rust doc ecosystem is that Cargo (the build tool) is able to generate all docs for all libs included in a project, including Rust itself, in static website.

@DjebbZ I think [Dynadoc](https://github.com/oakes/Dynadoc) is Clojure's analog
