### ISSUE TITLE
Expand article tree in full by default

### ISSUE THREAD

**Issue by ikitommi** [martinklepsch/cljdoc#30]
The navigation of the docs would be easier if the whole navigation tree could be open all the time, like [Gitbook](https://github.com/GitbookIO/gitbook) does.

**Comment by martinklepsch** [comment]
I think this should require only a minor tweak to the function responsible for rendering the article tree:
https://github.com/martinklepsch/cljdoc/blob/f725fb3677217182d88dbcc0340b09c8f511704c/src/cljdoc/renderers/html.clj#L282-L295

I'll leave this open as an good first issue. Good chance to contribute :)

**Comment by martinklepsch** [comment]
Fixed by #39
