### ISSUE TITLE
Trailing slash required in URLs

### ISSUE THREAD

**Issue by glts** [martinklepsch/cljdoc#35]
I had a minute or so of confusion until I realised that (some?) cljdoc URLs require a trailing slash.

For example, `https://cljdoc.xyz/d/group/artifact/version` is a 404.

I would expect the URL without trailing slash to be the canonical location, and the version with trailing slash to redirect there. Cheers!

**Comment by glts** [comment]
No strong argument or feelings here, but I think it is conventional in REST-ful URLs to use slashes only as separators between path elements. Logically the resource itself doesn’t need a delimiter at the end. (Compare links in Clojars for example.)

**Comment by pesterhazy** [comment]
This caused confusion on reddit: https://www.reddit.com/r/Clojure/comments/8ls9j4/a_new_clojure_documentation_effort/dzi1sue

I'd agree with @glts that no-trailing-slashes is more common.

Wouldn't it be possible to support both (ideally with one canonical version)? E.g. like this: https://www.scalescale.com/tips/nginx/nginx-remove-trailing-slash/

**Comment by martinklepsch** [comment]
@pesterhazy thanks that's a good pointer. I previously tried handling that at the Yada/Bidi level but that one line Nginx config is hard to beat (and I didn't get it to work either way :). 

The [nginx server block config](https://github.com/martinklepsch/cljdoc/blob/master/ops/image/cljdoc.xyz.conf) is part of this repo. Routes are in `routes.clj`.

Anyone of you maybe wants to open a PR? :)
