### ISSUE TITLE
CI build is failing due to memory usage

### ISSUE THREAD

**Issue by bfontaine** [martinklepsch/cljdoc#46]
:wave: Hello there,

I tried to generate the docs for [Datasplash](https://github.com/ngrunwald/datasplash) at <https://cljdoc.xyz/d/datasplash/datasplash/0.6.1/>, but the CI build failed because of a too-large memory usage when retrieving dependencies:

```
...
Retrieving beam-runners-local-java-core-2.3.0.jar from https://repo1.maven.org/maven2/ (2629k)
Retrieving beam-runners-google-cloud-dataflow-java-2.3.0.jar from https://repo1.maven.org/maven2/ (8348k)
./script/analyze.sh: line 25:    96 Killed                  boot -B --source-paths src --resource-paths resources --init "(require 'cljdoc.analysis.task)" cljdoc.analysis.task/analyze -p "$project" -v "$version" -j "$jar_path" sift --include "^cljdoc-edn" target -d /tmp/cljdoc-target/
Exited with code 137

Hint: Exit code 137 typically means the process is killed because it was running out of memory
Hint: Check if you can optimize the memory usage in your app
Hint: Max memory usage of this container is 4286750720
 according to /sys/fs/cgroup/memory/memory.max_usage_in_bytes
```

See [build #240](https://circleci.com/gh/martinklepsch/cljdoc-builder/240). I tried another time to be sure ([build #242](https://circleci.com/gh/martinklepsch/cljdoc-builder/242)) to no avail.

I don’t know how to fix this (besides raising the available memory).

**Comment by martinklepsch** [comment]
@bfontaine Hey, thanks for giving this a shot, I saw that build too. It seems I didn't correctly set the JAVA_OPTIONS on CircleCI, which I now fixed. Also ran another build for Datasplash, docs are here now:

https://cljdoc.xyz/d/datasplash/datasplash/0.6.1/

Will close this issue but feel free to ask any further questions. There's also #cljdoc on Slack if you feel like stopping by!  🙂 

Thanks for raising this and thanks for trying cljdoc! 🙌
