### ISSUE TITLE
Directories of projects/artifacts would be very useful

### ISSUE THREAD

**Issue by seancorfield** [martinklepsch/cljdoc#66]
* https://cljdoc.xyz/d could show a list of group IDs that have been processed,
* https://cljdoc.xyz/d/groupid could show a list of artifacts under that group ID

These would be consistent with expectations set by https://cljdoc.xyz/d/groupid/artifactid and would also make all the project documentation much more discoverable (since the home page is a static, curated set of projects).

**Comment by martinklepsch** [comment]
Here are some tips/pointers if anyone wants to take a stab at this:

Rendring code for artifact overview: 

https://github.com/martinklepsch/cljdoc/blob/0207d8d17744978a9ae453b19a6c0ce2c9833620/src/cljdoc/renderers/html.clj#L35

I think if you extend that multimethod to `:group/index` it will receive the same data so it should be mostly a matter of writing some hiccup 🙂 

Overview over groups would require slightly more work, take a look at how `grimoire-loader` retrieves the relevant data and you'll probably see what needs to be done.

**Comment by martinklepsch** [comment]
I added a page for https://cljdoc.xyz/d/groupid but didn't yet add one for the "everything" route. Might get to that later but captured it in the catch-all feedback thread for now: https://github.com/martinklepsch/cljdoc/issues/64#issuecomment-395840854
